// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV5XpIvL7eWwB0wONnPwFrYIZJ5qqMxnk',
    appId: '1:1064227831434:web:9db7ac95fe8efa07ab3773',
    messagingSenderId: '1064227831434',
    projectId: 'duel-quiz-multiplayer',
    authDomain: 'duel-quiz-multiplayer.firebaseapp.com',
    storageBucket: 'duel-quiz-multiplayer.firebasestorage.app',
    measurementId: 'G-75LEPWGL56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDew8gkuzCKlNEatMigj_fgzrhncH1BJd0',
    appId: '1:1064227831434:android:5644e9db5640b6eeab3773',
    messagingSenderId: '1064227831434',
    projectId: 'duel-quiz-multiplayer',
    storageBucket: 'duel-quiz-multiplayer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9W2odeHTelKSvgcW_qmM-q4DPL5LhRMo',
    appId: '1:1064227831434:ios:a80a55e0113a75b7ab3773',
    messagingSenderId: '1064227831434',
    projectId: 'duel-quiz-multiplayer',
    storageBucket: 'duel-quiz-multiplayer.firebasestorage.app',
    iosBundleId: 'com.fusionwave.duelMultiplayerQuiz',
  );
}
